name: task_mvp
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  drift: ^2.30.0
  drift_flutter: ^0.2.8
  sqlite3_flutter_libs: ^0.5.41
  path_provider: ^2.1.5
  path: ^1.9.1
  uuid: ^4.5.2
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0
  shimmer: ^3.0.0
  share_plus: ^12.0.1
  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.1   # âœ… keep this

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.24.0
  build_runner: ^2.4.8
  intl: ^0.19.0
  flutter_local_notifications: ^17.1.2
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
